title: 'Skity: 2D Vector Graphic Library'

theme: jekyll-theme-slate

highlighter: rouge

repository: "RuiwenTang/Skity"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
  - run_dev.sh